{{- if .Values.gitWebhookProxy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.gitWebhookProxy.ingress.gcp.enabled }}
    {{- if .Values.gitWebhookProxy.ingress.gcp.name }}
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.gitWebhookProxy.ingress.gcp.name }}
    {{- else if .Values.gitWebhookProxy.useCustomName }}
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.gitWebhookProxy.customName }}-frontend
    {{- else }}
    networking.gke.io/v1beta1.FrontendConfig: {{ template "gitwebhookproxy.name" . }}-frontend
    {{- end }}
{{- end }}
{{- if .Values.gitWebhookProxy.ingress.annotations }}
{{ toYaml .Values.gitWebhookProxy.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "gitwebhookproxy.labels.stakater" . | indent 4 }}
{{ include "gitwebhookproxy.labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "gitwebhookproxy.name" . }}
{{- end }}
spec:
  ingressClassName:  {{ .Values.gitWebhookProxy.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.gitWebhookProxy.ingress.host }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: {{ .Values.gitWebhookProxy.ingress.path }}
        backend:
        {{- if .Values.gitWebhookProxy.useCustomName }}
          service:
            name: {{ .Values.gitWebhookProxy.customName }}
            port:
              number: {{ .Values.gitWebhookProxy.servicePort }}
        {{- else }}
          service:
            name: {{ template "gitwebhookproxy.name" . }}
            port:
              number: {{ .Values.gitWebhookProxy.servicePort }}
        {{- end }}
  tls:
  - hosts:
    - {{ .Values.gitWebhookProxy.ingress.host }}
  {{- if .Values.gitWebhookProxy.ingress.tlsSecretName }}
    secretName: {{ .Values.gitWebhookProxy.ingress.tlsSecretName }}
  {{- end }}
{{- end }}